### ISSUE TITLE
Display username in notifications

### ISSUE THREAD

**Issue by siepra** [TryQuiet/ZbayMobile#87]
Right now I can't see the sender of messages in mobile notifications. We should show them.

See: https://material.io/design/platform-guidance/android-notifications.html#templates

**Comment by siepra** [comment]
https://github.com/ZbayApp/ZbayMobile/issues/88 should be completed first

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/988

**Comment by kingalg** [comment]
0.8.4
It's working.

**Comment by kingalg** [comment]
![Screenshot_20221205_111625](https://user-images.githubusercontent.com/68909168/205612228-36152398-59ef-4e60-9740-d082f6c31ce9.jpg)
