### ISSUE TITLE
White screen on startup, mobile, after loading screen

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/ZbayMobile#90]
Steps to reproduce:

1. fresh install of zbay
2. proceed through user registration

expected: user sees either a loading indicator or a working app.

actual: a white screen appears, with no message entry field or messages visible, and no loading indicator. this displayed for 30 seconds or more for me and so I restarted the app.

**Comment by siepra** [comment]
At this point proper behavior depends on env vars injected during build process. Should check if correct Zbay Channel address is provided on CI

**Comment by siepra** [comment]
App behavior is going to be changed after implementing communities (with nectar). Issue with white screen in startup should disappear after that

**Comment by siepra** [comment]
More descriptive ticket opened here https://github.com/TryQuiet/quiet/issues/811
