### ISSUE TITLE
Installing android app stops at starting Tor

### ISSUE THREAD

**Issue by EmiM** [TryQuiet/ZbayMobile#96]
AFAIK it happens only on my phone, others don't have this problem.

OnePlus 3
Android version: 9

**Comment by siepra** [comment]
We'll bind tor process to main application thread (instead of running it in background task) so I think all related problems should disappear. Although it'd be good to confirm that

**Comment by EmiM** [comment]
This task has been created a year ago, it's related to old mobile app and my old phone with old Android.
I think it can be closed, we have other tasks related to tor problems.
